version: '3.8'

services:
  # MySQL instance for ecommerce
  ecommerce-db:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network
    ports:
      - "3307:3306"

  # ecommerce-db application
  ecommerce-service:
    build:
      context: .  # Context is the current directory (ecommerce-service)
    ports:
      - "8080:8080"
    environment:
      SPRING_JDBC_URL: jdbc:mysql://ecommerce-db:3306/tuberiasperuanito_v1?createDatabaseIfNotExist=true
      SPRING_JDBC_USERNAME: root
      SPRING_JDBC_PASSWORD: rootpassword
      ENV_PROFILE: mysql
    depends_on:
      ecommerce-db:
        condition: service_healthy
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data: